### ISSUE TITLE
API docs loading issue due to incorrect MIME type of styles and scripts

### ISSUE THREAD

**Issue by johanrd** [NullVoxPopuli/ember-resources#1036]
1. Go here: https://ember-resources.pages.dev/functions/use.html
2. See that sub pages of the api docs refuse to load scripts and style because the MIME type is not supported:

<img width="980" alt="Screenshot 2023-11-07 at 13 32 55" src="https://github.com/NullVoxPopuli/ember-resources/assets/4601554/92d2500d-8e35-4cd6-96e0-78ffa23fc90f">

```log
Refused to apply style from 'https://ember-resources.pages.dev/functions/assets/highlight.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
use.html:1 Refused to apply style from 'https://ember-resources.pages.dev/functions/assets/custom.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
use.html:1 Refused to execute script from 'https://ember-resources.pages.dev/functions/assets/main.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
use.html:1 Refused to apply style from 'https://ember-resources.pages.dev/functions/assets/style.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
use.html:1 Refused to execute script from 'https://ember-resources.pages.dev/functions/assets/navigation.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
use.html:1 Refused to execute script from 'https://ember-resources.pages.dev/functions/assets/search.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```

**Comment by NullVoxPopuli** [comment]
For step 1, where'd you get that link?

Anywho, The underlying issue is all Cloudflare breaking things.
Here is the background: https://github.com/cloudflare/workers-sdk/issues/2240#issuecomment-1685032081

This caused it: https://github.com/cloudflare/workers-sdk/pull/2103

**Comment by NullVoxPopuli** [comment]
the page you're looking for is here: https://ember-resources.pages.dev/funcs/use.html

It seems the script that rewrites functions to funcs forgot about some links in the nav https://github.com/NullVoxPopuli/ember-resources/blob/main/.github/workflows/ci.yml#L261

**Comment by johanrd** [comment]
Ah, thanks, hehe,

Step -2: Go to the main site of the repository: https://github.com/NullVoxPopuli/ember-resources
Step -1: Click link to "API Reference" in section [Documentation](https://github.com/NullVoxPopuli/ember-resources#documentation)
<img width="368" alt="Screenshot 2023-11-07 at 14 19 35" src="https://github.com/NullVoxPopuli/ember-resources/assets/4601554/fb980d25-005a-4874-a509-f55a88c11c60">

this links you to https://ember-resources.pages.dev/modules

Step: 0: Click on "use"
<img width="960" alt="Screenshot 2023-11-07 at 14 19 28" src="https://github.com/NullVoxPopuli/ember-resources/assets/4601554/dd2d2da6-d48f-439e-96c5-d4d790361908">

this links you to  https://ember-resources.pages.dev/functions/use.html

**Comment by johanrd** [comment]
@NullVoxPopuli The docs navigation is still broken.

Could it be as easy as this?

https://github.com/NullVoxPopuli/ember-resources/blob/main/docs/typedoc.config.json
```diff
  "sidebarLinks": {
-    "link": "/functions/link.link.html",
-    "modifier": "/functions/modifier.modifier.html",
-    "service": "/functions/service.service.html",
-    "RemoteData": "/functions/util_remote_data.RemoteData.html",
-    "UpdateFrequency": "/functions/util_fps.UpdateFrequency.html",
-    "keepLatest": "/functions/util_keep_latest.keepLatest.html",
-    "debounce": "/functions/util_debounce.debounce.html",
-    "map": "/functions/util_map.map.html",
-    "trackedFunction": "/functions/util_function.trackedFunction.html",
-    "trackedTask": "/functions/util_ember_concurrency.trackedTask.html",
-    "helper": "/functions/util_helper.helper.html"
+    "link": "/funcs/link.link.html",
+    "modifier": "/funcs/modifier.modifier.html",
+    "service": "/funcs/service.service.html",
+    "RemoteData": "/funcs/util_remote_data.RemoteData.html",
+    "UpdateFrequency": "/funcs/util_fps.UpdateFrequency.html",
+    "keepLatest": "/funcs/util_keep_latest.keepLatest.html",
+    "debounce": "/funcs/util_debounce.debounce.html",
+    "map": "/funcs/util_map.map.html",
+    "trackedFunction": "/funcs/util_function.trackedFunction.html",
+    "trackedTask": "/funcs/util_ember_concurrency.trackedTask.html",
+    "helper": "/funcs/util_helper.helper.html"
  },
  ```

**Comment by NullVoxPopuli** [comment]
> Could it be as easy as this?

Probably! Do you want to submit a pr?

**Comment by NullVoxPopuli** [comment]
perhaps I need to not use cloudflare for typedoc deployments :(

**Comment by johanrd** [comment]
seems fixed now!

**Comment by johanrd** [comment]
**Reopening, the issue is back now.**

1. Go here: https://ember-resources.pages.dev/
2. Click on [resourceFactory](https://ember-resources.pages.dev/functions/resourceFactory.html)
3. See missing styles due to `Refused to apply style from '<URL>' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`:

<img width="1793" alt="Screenshot 2024-08-23 at 13 33 59" src="https://github.com/user-attachments/assets/5e626f69-5f59-4187-8118-94a303b783ec">

**Comment by NullVoxPopuli** [comment]
grrrrr this `functions` thing oof

**Comment by NullVoxPopuli** [comment]
ah, in protest, I moved the docs here to Vercel: https://ember-resources.nullvoxpopuli.com
