### ISSUE TITLE
Does RemoteData still exist?

### ISSUE THREAD

**Issue by MichalBryxi** [NullVoxPopuli/ember-resources#1125]
Trying to follow [this tutorial](https://tutorial.glimdown.com/11-requesting-data/1-using-remote-data) and bumping into following error:

```
Module not found: Error: Can't resolve './helpers/RemoteData' in ...
```

When trying:

```
{{#let
  (RemoteData
    "..."
  )
  as |request|
}}
  isLoading:
  {{request.isLoading}}
  data:
  {{request.value}}
{{/let}}
```

**Comment by NullVoxPopuli** [comment]
It does still exist! Tho it moved here:

https://reactive.nullvoxpopuli.com/functions/remote_data.RemoteData.html


That tutorial chapter should be updated to use the new import path, can you open an issue over there? 
(Or a PR?) 
Thanks!

**Comment by MichalBryxi** [comment]
Wanted to help out, but I'm bamboozled now. The path [in the tutorial](https://tutorial.glimdown.com/11-requesting-data/1-using-remote-data?showAnswer=0) seems correct?

![Screenshot 2024-04-29 at 21 24 26](https://github.com/NullVoxPopuli/ember-resources/assets/847473/56a72c29-2d76-4375-9538-9eb54b3b0c37)

But [the blame](https://github.com/NullVoxPopuli/limber/blame/main/apps/tutorial/public/docs/11-requesting-data/1-using-remote-data/answer.gjs) seems to be changed a while ago?

IDK, the status quo seems correct to me...

**Comment by NullVoxPopuli** [comment]
I may have updated it :sweat_smile:
