### ISSUE TITLE
Manual triggering?

### ISSUE THREAD

**Issue by backspace** [NullVoxPopuli/ember-resources#140]
I have a use case where I can rely on declarative fetching in most cases but I occasionally need to manually trigger a fetch after a process has completed. I’m currently [using `useTask`](https://github.com/cardstack/cardstack/commit/4982e26bae01c028dacc0c43d0a0df742b3782ac) because the existing code was already a task. Is there any way to manually trigger the task? A workaround would be to add something like a counter as part of the thunk that I increment to trigger a fetch, but that would be unfortunate 😆

Thanks for your work on this, I’m just now finally getting to try out the use/resources concepts and this addon seems like it’ll be helpful 🤩

**Comment by NullVoxPopuli** [comment]
I'm not sure if this is available, but you could call the update function?

https://github.com/NullVoxPopuli/ember-resources/blob/main/addon/-private/resources/ember-concurrency-task.ts#L54

**Comment by backspace** [comment]
hmm it’s `undefined` for me 🤔  I’m pretty unfamiliar with these ideas so maybe there’s another approach (it probably doesn’t need to be an Ember Concurrency task, for instance), but I wonder if this is a valid use case regardless?

**Comment by backspace** [comment]
With some [guidance](https://github.com/cardstack/cardstack/pull/1995#issue-716828744) I was able to [change to `useResource`](https://github.com/cardstack/cardstack/pull/1987/commits/d4866b68b7cb80a6a217e35d99c8f8e252aab27f) instead which opened up manual triggering 🎉
