### ISSUE TITLE
Potentially confusing example in README

### ISSUE THREAD

**Issue by abeforgit** [NullVoxPopuli/ember-resources#19]
The example for creating your own resource gives a good sense of how to do so, but the implementation of the doAsyncTask is doing some uncommon things (at least for me), and it's not immediately clear if this is "just an example" or if it demonstrates a potential gotcha.

Here's what I mean:

```js

  async doAsyncTask() {
    // <-- valuable information, makes it clear that args need to be consumed -->
    // need to consume potentially tracked data so that
    // update may be called when these args change
    let [ids] = this.args.positional;

    // <-- Is this something we always have to think about when using resources? or is this just
    // what the example task happens to be about? -->
    // defer to next (micro)task queue to not block UI
    // (and avoid double render bugs because we're about to set tracked data)
    await Promise.resolve();

    this.isRunning = true;
    this.error = undefined;

    try {
      // some long running stuff here
    } catch (e) {
      this.error = e
    }

    this.isRunning = false;
  }
```

Suggestion: if it isn't related to ember-resources, maybe simplify the example with a more common fetch call or something, and if it is, maybe clarify it further in the docs.

**Comment by NullVoxPopuli** [comment]
I've updated the readme, thoughts?

**Comment by abeforgit** [comment]
Looks good! Thanks for the update!
