### ISSUE TITLE
What is the expected behavior when I do `destroy(resourceInstance)`?

### ISSUE THREAD

**Issue by nag5000** [NullVoxPopuli/ember-resources#199]
I may have misunderstood something about how this is supposed to work... 
I tried to play around with it, but I ran into some oddities:
  - `registerDestructor`'s handler is not called (but yes, it's called if I update the args thunk, but should it be when I manually destroy a resource instance?)
  - the destroyed resource instance continues to be used when rendering, even if I rerender template.

```js
import { destroy, registerDestructor, isDestroyed, isDestroying } from '@ember/destroyable';

let resIndex = 0;

class MyResource extends Resource {
  constructor(owner, args, previous) {
    super(owner, args, previous);

    this.index = ++resIndex;
    console.log(this.index, 'initialized');

    registerDestructor(this, () => {
      console.log(this.index, 'destroyed');
    });
  }
}

export default class ApplicationController extends Controller {
  res = useResource(this, MyResource);

  @tracked doRender = true;

  @action
  destroyRes() {
    const res = this.res;
    destroy(res);

    console.log(res.index, 'destroying?', isDestroying(res));
    console.log(res.index, 'destroyed?', isDestroyed(res));

    setTimeout(() => {
      console.log(res.index, 'next run loop, destroyed?', isDestroyed(res));

      this.doRender = false;
      setTimeout(() => { this.doRender = true; }, 500);
    }, 0);
  }
}
```

```handlebars
{{#if this.doRender}}
  Current res index: {{this.res.index}}
  <br><button {{on "click" this.destroyRes}}>Destroy resource</button>
{{/if}}
```

1. logged `1 'initialized'` - OK
2. Click "Destroy resource" button
3. logged:
  - `1 'destroying?' true` - OK
  - `1 'destroyed?' false` - OK
  - `1 'next run loop, destroyed?' true` - OK
4. And... that's all. I expect that `1 'destroyed'` and `2 'initialized'` should be logged, but they are not.
5. "Current res index: 1" continues to render (after rerender too).

**Comment by NullVoxPopuli** [comment]
`this.res` isn't actually a reference to the resource -- it's a proxy -- so that's probably why you're observing that destruction isn't happening.

May I ask what you're trying to accomplish? maybe there is a different way? 
Like, why manually destroy a resource?

**Comment by nag5000** [comment]
> this.res isn't actually a reference to the resource -- it's a proxy

Ah, that's where I went wrong. Thank you!

I was thinking about how I could "invalidate" the resource declared in the controller when I leave the route.., something like `resetController -> isExiting? -> destroy(controller.resource)`. So that the next time I visit the route, a new instance of the resource will be used.

It seems I need to do this in a less sophisticated way :) 

Maybe something like
```js
export default class ApplicationController extends Controller {
  constructor() {
    super(...arguments);

    this.res = resetResource();
  }
  
  resetResource() {
    this.res = useResource(this, MyResource);
  } 
}
```

and call `controller.resetResource()` in `resetController`.

...or use `@tracked cacheBust = {}` and pass this into args thunk (but I don't really like this option).

Maybe there are some better options?

**Comment by NullVoxPopuli** [comment]
this is one of the main problems with controllers and why I avoid them at all costs -- they actively defy derived data patterns, and make everyone's lives harder. lol

so, in your case, I'd ask 
- what is your resource for?
- what data does it need?

because, if we follow derived data (getters, resources with manual lifecycle mangling, etc), things tend to "just work", and you don't need to all these silly controller hooks things.

like, based on your example with resetResource and constructor, I'd argue one of two things:
 - you don't need a resource, and you could use "just any vanilla class"
 - or, the resourcemanagement needs to be more hands off, and we have more details to discuss about what derives your resource data.

**Comment by nag5000** [comment]
> they make everyone's lives harder
> you don't need to all these silly controller hooks things

It's true.
I clearly understand that I can just make a "root" component in the route template, declare a resource in the component, and every time I visit the route there will be a new instance of the resource.

**Comment by nag5000** [comment]
Thanks for your help!

**Comment by NullVoxPopuli** [comment]
> if transition.to target route is 'foobar')

I think this would be doable via:
```js
class MyResource extends Resource {
  constructor(owner, args, previous) {
    super(owner, args, previous);
    
    if (args.positional[0] === 'foobar') {
      // copy previous state to `this`
    }
  }
}

class MyController extends Controller {
  @service router;
  
  myResource = useResource(this, MyResource, () => [this.router.currentRoute.name]);
}
```

Or, maybe it'd make more sense to extend from LifecycleResource in this case:

```js
class MyResource extends Resource {
  update() {
    if (this.args.positional[0] === 'foobar') {
      // do update stuff
      
      return;
    }
    
    // otherwise do nothing
  }
}

```
