### ISSUE TITLE
Backport ember-concurrency v1 fix to v3?

### ISSUE THREAD

**Issue by patocallaghan** [NullVoxPopuli/ember-resources#288]
I just came across this issue in our codebase while trying to use useTask. We use ember-concurrency v1 and ember auto import v1 in our app.

I found that the task value from useTask was never updating in the template which looks related to https://github.com/NullVoxPopuli/ember-resources/commit/0bf0122b684417fff0184ed03152841d34bd9fef

It might take us a while to upgrade to either embroider or ember auto import v2 in our app as we have a few old deps that rely on ember auto import v1. Is it possible to backport this fix to v3?

**Comment by NullVoxPopuli** [comment]
that fix was backported to here: https://github.com/NullVoxPopuli/ember-resources/commits/ember-auto-import-v1-support

released in 3.2.5.

If there is still an issue, can you shared your reproduction code?

**Comment by patocallaghan** [comment]
Doh! I had a look at the [releases page](https://github.com/NullVoxPopuli/ember-resources/releases) and it didn't have an entry for 3.2.5 so assumed  3.2.4 was the last one in 3.x. I upgraded to 3.2.5 and my issue is fixed 🎉 Thanks for working on this. It's great 🙌
