### ISSUE TITLE
Pass task properties through when using useTask

### ISSUE THREAD

**Issue by JimSchofield** [NullVoxPopuli/ember-resources#368]
It would be nice to be able to access the task properties when using `useTask`.  Currently, we are not able to see for example `.isRunning` or `isFinished` from a task passed to `useTask`

**Comment by NullVoxPopuli** [comment]
So, it looks like everything works fine with ember-concurrency@v2, _but_ none of the task instance properties work in ember-concurrency@v1.

woooooo

v1 failures: https://github.com/NullVoxPopuli/ember-resources/runs/5074958366?check_suite_focus=true
(default version in the test suite is v2)
