### ISSUE TITLE
Please can we see some examples?

### ISSUE THREAD

**Issue by roomman** [NullVoxPopuli/ember-resources#470]
Hi, love this addon and it's really helped to shift thinking about where and how we fetch data in some of our projects. Thanks.

I spent the morning refactoring one project away from `useResource` to `Resource.from`. I struggled a bit with the docs. In an earlier version of the repo you had practical examples in the README, which really helped with the start of my journey. They also helped me to understand how a `tracked-function` was different from a `Resource` etc.

This isn't a moan, because I can tell that the project is in-progress, and now may not be the best moment to commit to detailed docs, incase the API changes further. Just a feature request for the future - please can we have some examples (a bit of a "cookbook") of how and when to use each of the concepts?

**Comment by NullVoxPopuli** [comment]
Hi!!

Sorry about the confusion -- most of the examples still exist, but on each of the relevant API docs, for example: 
- https://ember-resources.pages.dev/classes/core.Resource
- https://ember-resources.pages.dev/modules/util_function#trackedFunction
- https://ember-resources.pages.dev/modules/util_function_resource#resource

I do agree the README as is has tipped too much the other way and now doesn't have enough content!

I think I kinda want to do what ember-modifier did and explain more of the thinking behind resources and go in to when you'd use specific types of resoureces and then link to the api docs for specifics. :thinking: 

thoughts?


I also like the idea of cookbooks in general. :thinking: 
I'd 100% be willing to take submissions for those (tho, I can provide a few as well)
Getting things started here: https://github.com/NullVoxPopuli/ember-resources/issues/471

**Comment by roomman** [comment]
> thoughts?

I will respond, I'm just taking some time to get my thoughts in order, and trying to think of some non-super-specific examples. 👍🏻

**Comment by roomman** [comment]
Hi @NullVoxPopuli, I was thinking how I would introduce this addon to someone in my team. Here’s where I got to:

Thanks to some new, fundamental building blocks in Ember (some “primitive apis”) it’s now possible to implement a concept called Resources. 

`ember-resources` by @NullVoxPopuli  is one implementation of that concept, inspired by [this article by @pzuraq](https://www.pzuraq.com/blog/introducing-use) and the various RFCs it references.  

The aim of the addon it to provide Ember users with a consistent way of addressing some common problems, like:

1. Having a component react to changes in application state without introducing unwanted side effects
2. Getting data to update in a controller without the need to refresh the entire route
3. Tracking the state of data you need to load asynchronously, in a non-blocking way

Below are before and after examples that demonstrate each of the above. For more detailed examples and further information, refer to the addon’s API documentation.

The core of the addon provides the APIs we need to make our own custom Resources. It also contains several pre-defined utilities, like ‘Tracked Functions’, that abstract the concept into efficient and easy to use tools. As we work through examples, we will cover how each might be used, and in what scenarios you would choose one option over another.

**Having a component react to changes in application state, without introducing unwanted side effects:**

Let’s imagine a component that fetches and displays a user’s profile picture. In this scenario, the image file (`my-profile-pic.jpeg`) lives in blob storage, and the file path (`/images/users/user1/my-profile-pic.jpeg`) is stored in an auth session. Before we can render the image we need to make an authenticated, asynchronous request to convert the file path into a downloadable URL (`https//:some-domain.com/images/users/user1/my-profile-pic.jpeg?token=someToken`).  When the user changes their profile picture the auth session is updated and the file path changes. At this point we want to fetch a new download URL.

Remember, we working with a component; it may be rendered in several places throughout our app (in the header, on the profile page etc.) and we want all instances of it to reflect any update. Our external request is asynchronous, but we don’t have the benefit of a route’s async hooks, and the class constructor and getters are not async. So what do we do? We might end up with something like this:

```javascript
// profile-picture.js
import Component from '@glimmer/component';
import { tracked } from '@glimmer/tracking';
import { inject as service } from '@ember/service';

import { getDownloadURL } from 'some-library';

export default class ProfilePictureComponent extends Component {
  @service session;

  @tracked downloadUrl;

  get filePath() {
    return this.session.data.authenticated.authUser.profilePicture || null;
  }

  get filePathObserver() {
    const path = this.filePath;
    this.getUrl();
    return path;
  }

  async getUrl() {
    if (!this.filePath) {
      return;
    }
    const url = await getDownloadURL(this.filePath);
    this.downloadUrl = url;
  }
}
```
```hbs
// profile-picture.hbs
<img src={{this.downloadUrl}} data-path={{this.filePathObserver}} />

```
In the above example, are using one getter (`filePath`) to trigger a second getter (`filePathObserver`) whose only purpose is to call a function (`getUrl`), that fetches some data asynchronously and sets a tracked property (`downloadUrl`). For reactivity to work the invocation in the template must be bound to `filePathObserver` as well as the tracked property. This approach works and when the user changes their profile picture, and file path changes, the component reacts. However, this is an anti-pattern and depends on a “side-effect”: fetching data is indirect and a side-effect of some other behaviour.

This is one of the many gaps Resources can fill. With `ember-resources` we can use a Tracked Function to simplify our component, like so:

```javascript
// profile-picture.js
import Component from '@glimmer/component';
import { inject as service } from '@ember/service';

import { trackedFunction } from 'ember-resources/util/function';
import { getDownloadURL } from 'some-library';

export default class ProfilePictureComponent extends Component {
  @service session;

  get filePath() {
    return this.session.data.authenticated.authUser.photoURL || null;
  }

  downloadUrl = trackedFunction(this, async () => {
    if (!this.filePath) {
      return;
    }
    const url = await getDownloadURL(this.filePath);
    return url;
  });
}
```
```hbs
// profile-picture.hbs
<img src={{this.downloadUrl.value}}/>
```
Under the hood, `trackedFunction` constructs a cached Resource. Into that Resource we pass `this` (our “destroyable context”) and the function we want to run. Optionally, we could also pass in an `initialValue`. 

Now, when `filePath` changes our tracked function re-runs and gets a new download url. We’ve removed the unwanted getter (`filePathObserver`) and the side-effect it represented. We don’t even need a tracked property. Instead, we bind `this.downloadUrl.value` to the template. `value` is one of the accessors defined in the underlaying Resource. Others include `isError`, `isLoading`, and `isPending`, giving us everything necessary, ‘off-the-shelf’ to craft a graceful user experience.

**Getting data to update in a controller without the need to refresh the entire route**
An example using paginated data?...

**Tracking the state of data you need to load asynchronously, in a non-blocking way**
An example of how Resource state can be used to give the user loading feedback and error handling?...

**Comment by roomman** [comment]
Not sure my profile-pic example is the best but I think this kind of example is what would help me to adopt the addon - the philosophy is really important, and there's no avoiding that what you're doing under the hood is super complex, but I think most devs are just looking for practical solutions and best practice examples to work from. 👍🏻

**Comment by NullVoxPopuli** [comment]
I still need to read this when I have time to really digest it -- thanks for sharing it!
In the mean time, I wanted to share a demo / repl of a newish Resource, `RemoteData` -- which _may_ help with common(?) uses: https://twitter.com/nullvoxpopuli/status/1527999026276311042

**Comment by NullVoxPopuli** [comment]
I've added some examples to `DOCS.md`, as well as the beginning of a "cookbook". More examples to come. If you have any questions and uncertainties, please let me know. 

Gonna close this issue for now tho. 

PRs super welcome for the cookbook. :D
