### ISSUE TITLE
Missing styles on functions pages

### ISSUE THREAD

**Issue by chrisvdp** [NullVoxPopuli/ember-resources#679]
**Examples**

https://ember-resources.pages.dev/functions/util_ember_concurrency.trackedTask.html
https://ember-resources.pages.dev/functions/util_debounce.debounce.html

**Console errors**

<img width="1424" alt="image" src="https://user-images.githubusercontent.com/1924349/201967851-f636b4ca-12b1-458f-a6c0-f2ca4ca4f0c5.png">

It seems like the path for nested pages is being added to the CSS file path.

**Comment by chrisvdp** [comment]
Reading closer, this seems to load the content from the home page instead of the content I would expect to see on the page.

**Comment by NullVoxPopuli** [comment]
related:
 - https://github.com/TypeStrong/typedoc/issues/2111
 - https://github.com/cloudflare/wrangler2/issues/2240

**Comment by NullVoxPopuli** [comment]
Should be resolved now. sorry about that.
