### ISSUE TITLE
useFunction() does not work when promise is returned and function is not async

### ISSUE THREAD

**Issue by BryanHunt** [NullVoxPopuli/ember-resources#72]
If you create a useFunction() with the form:

`useFunction(this, (state, ...args) => { return this.store.query(...) }, () => [...]);`

it will not work correctly.  The function must be declared `async` as in:

`useFunction(this, async (state, ...args) => { return this.store.query(...) }, () => [...]);`

**Comment by NullVoxPopuli** [comment]
Resolved by https://github.com/NullVoxPopuli/ember-resources/pull/81
