### ISSUE TITLE
Incorrect value returned when last task was dropped

### ISSUE THREAD

**Issue by rpemberton** [NullVoxPopuli/ember-resources#835]
The value from the dropped task (`null`) is being returned instead of returning the value from the last non dropped task. 

I expect this affects not only dropped tasks but cancelled tasks in general.

PR where bug was introduced: #808 
Conversation: https://github.com/NullVoxPopuli/ember-resources/pull/808#discussion_r1140458269

PR incoming.

**Comment by NullVoxPopuli** [comment]
Released in 5.6.4: https://github.com/NullVoxPopuli/ember-resources/releases/tag/ember-resources%405.6.4
