### ISSUE TITLE
A real world example(s)?

### ISSUE THREAD

**Issue by MichalBryxi** [NullVoxPopuli/ember-resources#90]
I'm having a hard time understanding what is a resource and when to use one. I think an example that shows a case where you  use this library to solve standard problem would be nice.

**Comment by NullVoxPopuli** [comment]
That's fair. 🤔 
I just released this a bit ago: https://github.com/NullVoxPopuli/ember-array-map-resource
But that's _very niche / specific_. 🙃 

Maybe something interacting with ember-data would be a good example to put to the ember-resources README.

Like,
```js
class extends Component {
  @service store;

  someRecord = useFunction(this, (, id) => {
     return this.store.findRecord('some-record', id);
  }, () => this.args.id);
}
```
`someRecord.value` (.value is required for function-resources) would be:
 - undefined initially
 - will not call findRecord until `someRecord.value` is accessed
 - "eventually" be an ember-data Model
 - if `@id` / `this.args.id` change, the function is run again, `someRecord.value` keeps its old value until the function re-resolves.
 
I'm sure the README phrasing can be better, but the gist is that they solve the problem of "reactive lazy data that resolves eventually".

Like, without the resource, you'd need to find a way to call a function that calls findRecord yourself.
And then you'd need to also figure out a way to re-call that function when your `@id` changes.

**Comment by NullVoxPopuli** [comment]
Here are some additional examples: https://github.com/NullVoxPopuli/ember-data-resources/

**Comment by MichalBryxi** [comment]
I think you covered (at least mine) most pressing questions. Now I think there is a value of cross linking ember-resources and ember-data-resources in the documentation to show people how things can be done. I created #120 for that.

**Comment by MichalBryxi** [comment]
This one can be probably closed now.
