### ISSUE TITLE
TypeScript error when using `trackedTask` with `ember-concurrency`: not assignable to parameter of type `TaskIsh<string[], unknown>`

### ISSUE THREAD

**Issue by johanrd** [NullVoxPopuli/ember-resources#903]
When using the trackedTask function provided by ember-resources/util/ember-concurrency, a TypeScript error occurs when the generator function is assigned as a task:

```typescript
import { tracked } from '@glimmer/tracking';
import { restartableTask, timeout } from 'ember-concurrency';
import { task as trackedTask } from 'ember-resources/util/ember-concurrency';

class Demo {
  @tracked id = 1;

  last = trackedTask(this, this.searchTask, () => [this.id]);

  @restartableTask
  *searchTask(id: number) {
    yield timeout(200);
    yield fetch('...');

    return 'the-value';
  }
}
```
The TypeScript compiler throws an error at the assignment of `this.searchTask` in `last`:

```
Argument of type '(id: number) => Generator<Yieldable<void> | Promise<Response>, string, unknown>' is not assignable to parameter of type 'TaskIsh<number[], unknown>'
```

Could this be an issue with the type definitions in ember-resources?

**Comment by johanrd** [comment]
Update: rewriting the [Demo class from the docs](https://ember-resources.pages.dev/funcs/util_ember_concurrency.trackedTask) to the async syntax of ember-concurrency, seems to fix the type errors:

```typescript
class Demo {
  @tracked id = 1;

  searchTask = restartableTask(async () => {
    await timeout(200);
    await fetch('...');

    return 'the-value';
  })

  last = trackedTask(this, this.searchTask, () => [this.id]);

}
```

**Comment by NullVoxPopuli** [comment]
ah yeah -- I must have missed the docs update when I added support for ember-concurrency's new types. :upside_down_face: 

If you want to submit a PR that updates those docs, that'd be a huge help! <3

**Comment by johanrd** [comment]
thanks, yes, sure. 

While at it – the documentation page of [task](https://ember-resources.pages.dev/funcs/util_ember_concurrency.task) and [trackedTask](https://ember-resources.pages.dev/funcs/util_ember_concurrency.trackedTask) seems to be exactly similar. Are they meant to be aliases, just a missing cleanup, or other? thanks,

**Comment by NullVoxPopuli** [comment]
Yup, alias is here: https://github.com/NullVoxPopuli/ember-resources/blob/ea954c5/ember-resources/src/util/ember-concurrency.ts#L75
