### ISSUE TITLE
Maximum call stack exceeded & others

### ISSUE THREAD

**Issue by MichalBryxi** [NullVoxPopuli/ember-resources#98]
While trying to reproduce #91 in a sandbox I bumped on a very strange behaviour. I can't tell which part of the ecosystem is misbehaving (might be not fault of `ember-resources`), but it is somewhat alarming because it crashes the app and it's somewhat random. Also the message / error is different from browser to browser. And in some cases (Firefox) disappears when I _don't_ use `@cached` in one particular place (but that might be just a matter of luck).

- Edge: `lazy_load.js:75 Uncaught RangeError: Maximum call stack size exceeded.`
- Firefox/Safari: `Error while processing route: index – "decorator is not a function. (In 'decorator(target, property, desc)', 'decorator' is undefined)"`

![Screenshot 2021-07-29 at 10 10 49](https://user-images.githubusercontent.com/847473/127465225-2a8ec984-a4ed-4dc5-90aa-e11001f666b5.png)
![Screenshot 2021-07-29 at 10 10 58](https://user-images.githubusercontent.com/847473/127465238-2dc6d2c5-fb8b-493f-b833-4e39d1abd5da.png)

I created a full reproduction repo here: https://gitlab.com/michal-bryxi/bugreport/ember-resources-bugreport

If this is a concern of other part of the Ember ecosystem, I'm happy to re-report.

**Comment by NullVoxPopuli** [comment]
Looks like you're missing https://github.com/ember-polyfills/ember-cached-decorator-polyfill

**Comment by MichalBryxi** [comment]
🤦  Remove the keyboard from me
